// Generated by CoffeeScript 2.7.0
(function() {
  // (params) -> body
  var anonymousFunction, greet, result, result2, sayHello, square, squares;

  sayHello = function(name) {
    return "Hello there, " + name;
  };

  greet = (name) => {
    return "Hello there, " + name;
  };

  square = function(x) {
    return Math.pow(x, 2);
  };

  console.log(sayHello("Joanna"));

  console.log(greet("Joanna"));

  console.log(square(4));

  squares = [1, 2, 3, 4, 5].map(square); // pass function by name

  result = (function(x) {
    return x * 5;
  })(16); // call anonymous function

  console.log(squares);

  console.log(result);

  anonymousFunction = function(x) {
    return x * 5;
  };

  result2 = anonymousFunction(16);

  console.log(result2);

}).call(this);
